name: Produce artifacts

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out repository
        uses: actions/checkout@v3

      - name: archive requirement profiles
        run: zip -r requirement_profiles.zip shacl/

      - name: upload zipped artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-requirement-profiles
          path: requirement_profiles.zip
