name: build zip with latest commit hash
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: check out repository
        uses: actions/checkout@v3

      - name: Archive Repository
        run: zip -r archive.zip . -x "*.git*" -x "*.github*"

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Upload to zip-archive branch
        run: |
          git checkout --orphan temp-branch
          git rm -rf .
          git add -f archive.zip
          git commit -m "Upload latest zip archive"
          git branch -M zip-archive
          git push -fu origin zip-archive
